title: ChinaComX 
description: An academic project exploring beyond the Silk Road.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: minima
